{% set name = "dtool_info" %}
{% set reponame = "dtool-info" %}
{% set author = "jic-dtool" %}
{% set version = "0.15.0" %}
{% set sha256 = "c5a0077345fe7dd47cb67138a1933b7b617f7437831537822d7d9b5c2f752877" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - jinja2
    - pygments
test:
  imports:
    - dtool_info
    - dtool_info.dataset
    - dtool_info.inventory
    - dtool_info.overlay
    - dtool_info.templates
    - dtool_info.utils
  commands:
    - dtool diff --help
    - dtool ls --help
    - dtool summary --help
    - dtool item --help
    - dtool identifiers --help
    - dtool verify --help
    - dtool overlay --help
    - dtool inventory --help
    - dtool uuid --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for getting information about datasets'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
