{% set name = "dtool_info" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-info/dtool-info-{{ version }}.tar.gz
  sha256: 06e062f4fb0d011d4be1dbd1c5785db6f6d01cecce2e547e34ef4bf6bbd9474c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - jinja2
    - pygments
test:
  imports:
    - dtool_info
    - dtool_info.dataset
    - dtool_info.inventory
    - dtool_info.overlay
    - dtool_info.templates
    - dtool_info.utils
  commands:
    - dtool diff --help
    - dtool ls --help
    - dtool summary --help
    - dtool item --help
    - dtool identifiers --help
    - dtool verify --help
    - dtool overlay --help
    - dtool inventory --help
    - dtool uuid --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool-info
  license: MIT
  license_file: LICENSE.rst
  summary: dtool CLI commands for getting information about datasets
  doc_url: https://github.com/jic-dtool/dtool-info
  dev_url: https://github.com/jic-dtool/dtool-info

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
