travis:
  secure:
    BINSTAR_TOKEN: fod/ZTeU6iSXJOc3QNTGrxiu0YrPGNwbM9Xk0cj33BpqUH+ljCSLwB3v5G6jwjHK9JSKGqMSJ4a5qSpRPq1o1a3KF8LMsBQz/r1QzbC/0k5kjS9zJ/c+4Cz2cyQ7gAJRgdASocdgGfOhzuSAiquEp6qNKXOygW/Ygiqv0/781gV1HOZyNA9QoCsRYq2gC5MFXWKqi9ZwKZKZMUyttjrnIeWxvLIZMQi0paB7CySJp703ECeAeWfgxy3/QQS+HdWjVISOjqHCfGs+LeF53J9FB0uEUftCk1y2neqtf26iMCVW1e+JvY3DCwLUPNHfikAgjgGfK8M99gFlS6D7V2gt3yeJspDPhnOGpNvDD4pTHHPLpECYMDcCzTLAZxxcNt3GF/1ZL6FT+WIh26e2k6qszvFp1C9dzr0/MP6qQebxgBqmH9+HgSxrfJ6zs+yJmPWi/GxtufPNjlTATXuLekbDxrgcCAh0tBLqTp0SjUvpE+yxgyS2zqWsHnskHfFh3DANS4LQUA3nZSQVuUJZFD4xmPVGqZixPmmc2L7+PLqMgrHGMnheb9bewejNZvXZ+QPg4uh5gf/AW70dELPAn8mydRx1MczrXBFYPRW7JhWZ6ks8I3/iVNNXYqzFZxV0jgI8InsxuYAR+jpFZAFAi8MU7uv49JL6blRYZT6H77kD0g4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
